#!/usr/bin/env bash
# ==============================================================================
# Step 5: Cloud IDS Threat Alert & Traffic Log Verification
# Queries Cloud Logging for ids.googleapis.com/threat and ids.googleapis.com/traffic
# alerts generated by the Packet Mirroring + Attack Simulation workflow.
# ==============================================================================
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ROOT_DIR="$(cd "${SCRIPT_DIR}/.." && pwd)"
CONFIG_FILE="${ROOT_DIR}/config.yaml"

CLI_PROJECT_ID=""
DRY_RUN=false
WAIT_FOR_LOGS=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --project)
            CLI_PROJECT_ID="$2"
            shift 2
            ;;
        --wait)
            WAIT_FOR_LOGS=true
            shift
            ;;
        --dry-run)
            DRY_RUN=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

cfg_get() {
    local key_path="$1"
    local default_val="$2"
    if [ -f "${CONFIG_FILE}" ]; then
        python3 -c '
import sys, yaml
with open(sys.argv[1], "r", encoding="utf-8") as f:
    data = yaml.safe_load(f) or {}
val = data
for k in sys.argv[2].split("."):
    if isinstance(val, dict):
        val = val.get(k)
    else:
        val = None
        break
print(val if val not in (None, "") else sys.argv[3])
' "${CONFIG_FILE}" "${key_path}" "${default_val}" 2>/dev/null || echo "${default_val}"
    else
        echo "${default_val}"
    fi
}

PROJECT_ID="${CLI_PROJECT_ID:-${PROJECT_ID:-$(cfg_get "project_id" "YOUR_PROJECT_ID")}}"
MAX_RESULTS="$(cfg_get "verification.max_results" "25")"
POLL_ATTEMPTS="$(cfg_get "verification.poll_attempts" "6")"
POLL_INTERVAL="$(cfg_get "verification.poll_interval_sec" "15")"

validate_gcp_id() {
    local val="$1"
    local label="$2"
    if [[ ! "$val" =~ ^[a-z][a-z0-9-]{4,61}[a-z0-9]$ ]]; then
        echo -e "${RED}Error: Invalid ${label} '${val}'. Please set a valid project_id in config.yaml or pass --project <PROJECT_ID>.${NC}"
        exit 1
    fi
}

if [[ "$PROJECT_ID" == "YOUR_PROJECT_ID" || -z "$PROJECT_ID" ]]; then
    if [[ "$DRY_RUN" == "false" ]]; then
        echo -e "${RED}Error: project_id is still set to placeholder 'YOUR_PROJECT_ID'.${NC}"
        echo -e "Update ${CYAN}project_id${NC} in ${GREEN}config.yaml${NC} or pass ${GREEN}--project <PROJECT_ID>${NC}."
        exit 1
    fi
else
    validate_gcp_id "$PROJECT_ID" "PROJECT_ID"
fi

THREAT_FILTER='resource.type="ids.googleapis.com/Endpoint" AND logName:"ids.googleapis.com%2Fthreat"'
TRAFFIC_FILTER='resource.type="ids.googleapis.com/Endpoint" AND logName:"ids.googleapis.com%2Ftraffic"'

echo -e "${BLUE}====================================================================${NC}"
echo -e "${BLUE}${BOLD}   Step 5: Cloud IDS Threat Alert Verification (Cloud Logging)      ${NC}"
echo -e "${BLUE}====================================================================${NC}"
echo -e "  ${CYAN}Project ID:${NC}         ${PROJECT_ID}"
echo -e "  ${CYAN}Threat Log Filter:${NC}  ${THREAT_FILTER}"
echo -e "  ${CYAN}Cloud Console URL:${NC}  https://console.cloud.google.com/net-security/ids/threats?project=${PROJECT_ID}"
echo ""

if [[ "$DRY_RUN" == "true" ]]; then
    echo -e "${YELLOW}[DRY-RUN] Would query Cloud Logging with:${NC}"
    echo "gcloud logging read '${THREAT_FILTER}' --project='${PROJECT_ID}' --limit=${MAX_RESULTS} --format='table(timestamp, jsonPayload.alert_severity, jsonPayload.name, jsonPayload.type, jsonPayload.source_ip_address, jsonPayload.destination_ip_address)'"
    exit 0
fi

ATTEMPT=1
THREAT_JSON="[]"

while [[ $ATTEMPT -le $POLL_ATTEMPTS ]]; do
    THREAT_JSON=$(gcloud logging read "${THREAT_FILTER}" \
        --project="${PROJECT_ID}" \
        --limit="${MAX_RESULTS}" \
        --format="json" 2>/dev/null || echo "[]")

    COUNT=$(python3 -c 'import json, sys; data = json.loads(sys.stdin.read() or "[]"); print(len(data))' <<< "${THREAT_JSON}")

    if [[ "$COUNT" -gt 0 ]]; then
        echo -e "${GREEN}✓ Detected ${COUNT} Cloud IDS threat alert(s) in Cloud Logging!${NC}\n"
        break
    fi

    if [[ "$WAIT_FOR_LOGS" == "false" || $ATTEMPT -eq $POLL_ATTEMPTS ]]; then
        break
    fi

    echo -e "${YELLOW}  [Attempt ${ATTEMPT}/${POLL_ATTEMPTS}] Waiting ${POLL_INTERVAL}s for threat alerts to appear in Cloud Logging...${NC}"
    sleep "${POLL_INTERVAL}"
    ATTEMPT=$((ATTEMPT + 1))
done

gcloud logging read "${THREAT_FILTER}" \
    --project="${PROJECT_ID}" \
    --limit="${MAX_RESULTS}" \
    --format="table[box](timestamp:label=TIMESTAMP, jsonPayload.alert_severity:label=SEVERITY, jsonPayload.threat_id:label=THREAT_ID, jsonPayload.name:label=SIGNATURE_NAME, jsonPayload.type:label=CATEGORY, jsonPayload.source_ip_address:label=ATTACKER_IP, jsonPayload.destination_ip_address:label=TARGET_IP)"

echo -e "\n${CYAN}Checking sample mirrored traffic logs (ids.googleapis.com/traffic):${NC}"
gcloud logging read "${TRAFFIC_FILTER}" \
    --project="${PROJECT_ID}" \
    --limit=5 \
    --format="table[box](timestamp:label=TIMESTAMP, jsonPayload.application:label=APP, jsonPayload.ip_protocol:label=PROTO, jsonPayload.source_ip_address:label=SRC_IP, jsonPayload.destination_ip_address:label=DST_IP, jsonPayload.destination_port:label=DST_PORT)"
